apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hime
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hime
    app.kubernetes.io/part-of: ci10t-776-0045-app
  name: devfile-sample-hime
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hime
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hime
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0045-tenant/ci10t-776-0045-app/devfile-sample-hime@sha256:0b66e0287ef45ba8b848b43ae4c4aafd5b3cd0d2afa58ff45716906fd627e9d2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
